apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dsn6eoeri-go 
  janus-idp.io/tekton: dsn6eoeri-go
  backstage.io/kubernetes-id: dsn6eoeri-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dsn6eoeri-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml